import { createContext, useContext, useState, ReactNode, useCallback } from 'react';

type Language = 'kk' | 'ru' | 'en';

interface Translations {
  [key: string]: {
    kk: string;
    ru: string;
    en: string;
  };
}

const translations: Translations = {
  // Navigation
  'nav.dashboard': { kk: 'Басты бет', ru: 'Главная', en: 'Dashboard' },
  'nav.tickets': { kk: 'Тикеттер', ru: 'Заявки', en: 'Tickets' },
  'nav.aiChat': { kk: 'AI Чат', ru: 'AI Чат', en: 'AI Chat' },
  'nav.analytics': { kk: 'Аналитика', ru: 'Аналитика', en: 'Analytics' },
  'nav.reports': { kk: 'Есептер', ru: 'Отчеты', en: 'Reports' },
  'nav.assets': { kk: 'Активтер', ru: 'Активы', en: 'Assets' },
  'nav.assets.panel': { kk: 'Панель', ru: 'Панель', en: 'Panel' },
  'nav.assets.computers': { kk: 'Компьютерлер', ru: 'Компьютеры', en: 'Computers' },
  'nav.assets.monitors': { kk: 'Мониторлар', ru: 'Мониторы', en: 'Monitors' },
  'nav.assets.software': { kk: 'Бағдарламалық қамтамасыз ету', ru: 'Программное обеспечение', en: 'Software' },
  'nav.assets.networkDevices': { kk: 'Желілік құрылғылар', ru: 'Сетевые устройства', en: 'Network Devices' },
  'nav.assets.devices': { kk: 'Құрылғылар', ru: 'Устройства', en: 'Devices' },
  'nav.assets.printers': { kk: 'Принтерлер', ru: 'Принтеры', en: 'Printers' },
  'nav.assets.cartridges': { kk: 'Картридждер', ru: 'Картриджи', en: 'Cartridges' },
  'nav.assets.consumables': { kk: 'Шығын материалдары', ru: 'Расходные материалы', en: 'Consumables' },
  'nav.assets.phones': { kk: 'Телефондар', ru: 'Телефоны', en: 'Phones' },
  'nav.assets.racks': { kk: 'Стойкалар', ru: 'Стойки', en: 'Racks' },
  'nav.assets.cases': { kk: 'Корпустар', ru: 'Корпуса', en: 'Cases' },
  'nav.assets.powerDistribution': { kk: 'Қуат таратқыштар', ru: 'Распределители питания', en: 'Power Distribution' },
  'nav.assets.passiveDevices': { kk: 'Пассивті құрылғылар', ru: 'Пассивные устройства', en: 'Passive Devices' },
  'nav.assets.unmanagedAssets': { kk: 'Басқарылмайтын активтер', ru: 'Неуправляемые активы', en: 'Unmanaged Assets' },
  'nav.assets.cables': { kk: 'Кабельдер', ru: 'Кабели', en: 'Cables' },
  'nav.assets.simCards': { kk: 'SIM-карта элементтері', ru: 'SIM-карта элементы', en: 'SIM Card Items' },
  'nav.assets.vpn': { kk: 'VPN', ru: 'VPN', en: 'VPN' },
  'nav.assets.reportAnalytics': { kk: 'Есептер аналитикасы', ru: 'Аналитика отчетов', en: 'Report Analytics' },
  'nav.assets.global': { kk: 'Ғаламдық', ru: 'Глобально', en: 'Global' },
  'nav.knowledge': { kk: 'Білім қоры', ru: 'База знаний', en: 'Knowledge Base' },
  'nav.tools': { kk: 'Құралдар', ru: 'Инструменты', en: 'Tools' },
  'nav.ppr': { kk: 'ППР', ru: 'ППР', en: 'PPR' },
  'nav.tools.projects': { kk: 'Жобалар', ru: 'Проекты', en: 'Projects' },
  'nav.tools.reminders': { kk: 'Еске салулар', ru: 'Напоминания', en: 'Reminders' },
  'nav.tools.rssFeed': { kk: 'RSS таспасы', ru: 'RSS лента', en: 'RSS Feed' },
  'nav.tools.knowledgeBase': { kk: 'Білім қоры', ru: 'База знаний', en: 'Knowledge Base' },
  'nav.tools.bookings': { kk: 'Брондаулар', ru: 'Бронирования', en: 'Bookings' },
  'nav.tools.reports': { kk: 'Есептер', ru: 'Отчёты', en: 'Reports' },
  'nav.tools.savedSearches': { kk: 'Сақталған іздеу сұраулары', ru: 'Сохраненные поисковые запросы', en: 'Saved Search Queries' },
  'nav.tools.cartography': { kk: 'Картография', ru: 'Картография', en: 'Cartography' },
  'nav.tools.detailedReports': { kk: 'Толық есептер', ru: 'Подробные отчеты', en: 'Detailed Reports' },
  'nav.tools.ipAddressing': { kk: 'IP адрестеу', ru: 'IP Addressing', en: 'IP Addressing' },
  'nav.news': { kk: 'Жаңалықтар', ru: 'Новости', en: 'News' },
  'nav.messages': { kk: 'Хабарламалар', ru: 'Сообщения', en: 'Messages' },
  'nav.videoConferences': { kk: 'Бейне конференциялар', ru: 'Видеоконференции', en: 'Video Conferences' },
  'nav.profile': { kk: 'Профиль', ru: 'Профиль', en: 'Profile' },
  'nav.logout': { kk: 'Шығу', ru: 'Выход', en: 'Logout' },
  'nav.admin': { kk: 'Әкімшілік', ru: 'Администрирование', en: 'Administration' },
  'nav.users': { kk: 'Қолданушылар', ru: 'Пользователи', en: 'Users' },
  'nav.departments': { kk: 'Бөлімдер', ru: 'Отделы', en: 'Departments' },
  'nav.categories': { kk: 'Категориялар', ru: 'Категории', en: 'Categories' },
  'nav.sla': { kk: 'SLA Саясаты', ru: 'SLA Политики', en: 'SLA Policies' },
  'nav.settings': { kk: 'Параметрлер', ru: 'Настройки', en: 'Settings' },
  'nav.2fa': { kk: '2FA орнату', ru: 'Настройка 2FA', en: '2FA Setup' },
  'nav.settings.dropdowns': { kk: 'Ашылмалы тізімдер', ru: 'Выпадающие списки', en: 'Dropdowns' },
  'nav.settings.components': { kk: 'Компоненттер', ru: 'Компоненты', en: 'Components' },
  'nav.settings.notifications': { kk: 'Хабарландырулар', ru: 'Уведомления', en: 'Notifications' },
  'nav.settings.serviceLevels': { kk: 'Қызмет көрсету деңгейлері', ru: 'Уровни обслуживания', en: 'Service Levels' },
  'nav.settings.general': { kk: 'Жалпы', ru: 'Общие', en: 'General' },
  'nav.settings.uniqueField': { kk: 'Бірегей өріс', ru: 'Уникальное поле', en: 'Unique Field' },
  'nav.settings.automaticActions': { kk: 'Автоматты әрекеттер', ru: 'Автоматические действия', en: 'Automatic Actions' },
  'nav.settings.authentication': { kk: 'Аутентификация', ru: 'Аутентификация', en: 'Authentication' },
  'nav.settings.receivers': { kk: 'Алушылар', ru: 'Получатели', en: 'Receivers' },
  'nav.settings.externalLinks': { kk: 'Сыртқы сілтемелер', ru: 'Внешние ссылки', en: 'External Links' },
  'nav.settings.plugins': { kk: 'Плагиндер', ru: 'Плагины', en: 'Plugins' },
  'nav.settings.objectManagement': { kk: 'Объектілерді басқару', ru: 'Управление объектами', en: 'Object Management' },
  'nav.notifications': { kk: 'Хабарландырулар', ru: 'Уведомления', en: 'Notifications' },
  'nav.notificationSettings': { kk: 'Хабарландыру параметрлері', ru: 'Настройки уведомлений', en: 'Notification Settings' },
  'nav.support': { kk: 'Қолдау', ru: 'Поддержка', en: 'Support' },
  'nav.support.panel': { kk: 'Панель', ru: 'Панель', en: 'Panel' },
  'nav.support.createTicket': { kk: 'Өтінім жасау', ru: 'Создание заявки', en: 'Create Ticket' },
  'nav.support.ppr': { kk: 'ППР', ru: 'ППР', en: 'PPR' },
  'nav.support.problems': { kk: 'Мәселелер', ru: 'Проблемы', en: 'Problems' },
  'nav.support.changes': { kk: 'Өзгерістер', ru: 'Изменения', en: 'Changes' },
  'nav.support.planning': { kk: 'Жоспарлау', ru: 'Планирование', en: 'Planning' },
  'nav.support.statistics': { kk: 'Статистика', ru: 'Статистика', en: 'Statistics' },
  'nav.support.periodicTickets': { kk: 'Мерзімді өтінімдер', ru: 'Периодические заявки', en: 'Periodic Tickets' },
  'nav.management': { kk: 'Басқару', ru: 'Управление', en: 'Management' },
  'nav.management.licenses': { kk: 'Лицензиялар', ru: 'Лицензии', en: 'Licenses' },
  'nav.management.budgets': { kk: 'Бюджеттер', ru: 'Бюджеты', en: 'Budgets' },
  'nav.management.suppliers': { kk: 'Жеткізушілер', ru: 'Поставщики', en: 'Suppliers' },
  'nav.management.contacts': { kk: 'Байланыстар', ru: 'Контакты', en: 'Contacts' },
  'nav.management.contracts': { kk: 'Шарттар', ru: 'Договоры', en: 'Contracts' },
  'nav.management.documents': { kk: 'Құжаттар және есептілік', ru: 'Документы и отчётность', en: 'Documents and Reports' },
  'nav.management.phoneLines': { kk: 'Телефон желілері', ru: 'Телефонные линии', en: 'Phone Lines' },
  'nav.management.certificates': { kk: 'Сертификаттар', ru: 'Сертификаты', en: 'Certificates' },
  'nav.management.dataCenters': { kk: 'Дата-орталықтар', ru: 'Дата-центры', en: 'Data Centers' },
  'nav.management.clusters': { kk: 'Кластерлер', ru: 'Кластеры', en: 'Clusters' },
  'nav.management.domains': { kk: 'Домендер', ru: 'Домены', en: 'Domains' },
  'nav.management.complexes': { kk: 'Кешендер', ru: 'Комплексы', en: 'Complexes' },
  'nav.management.databases': { kk: 'Дерекқорлар', ru: 'Базы данных', en: 'Databases' },
  'nav.administration': { kk: 'Әкімшілік', ru: 'Администрирование', en: 'Administration' },
  'nav.administration.groups': { kk: 'Топтар', ru: 'Группы', en: 'Groups' },
  'nav.administration.organizations': { kk: 'Бөлімдер', ru: 'Отделы', en: 'Departments' },
  'nav.administration.rules': { kk: 'Ережелер', ru: 'Правила', en: 'Rules' },
  'nav.administration.directories': { kk: 'Анықтамалықтар', ru: 'Справочники', en: 'Directories' },
  'nav.administration.profiles': { kk: 'Профильдер', ru: 'Профили', en: 'Profiles' },
  'nav.administration.notificationQueue': { kk: 'Хабарландыру кезегі', ru: 'Очередь уведомлений', en: 'Notification Queue' },
  'nav.administration.logs': { kk: 'Логтар', ru: 'Логи', en: 'Logs' },
  'nav.administration.equipment': { kk: 'Жабдық', ru: 'Оборудование', en: 'Equipment' },
  'nav.administration.glpiInventory': { kk: 'GLPI Inventory', ru: 'GLPI Inventory', en: 'GLPI Inventory' },
  'nav.administration.forms': { kk: 'Формалар', ru: 'Формы', en: 'Forms' },

  // Roles
  'role.admin': { kk: 'Әкімші', ru: 'Администратор', en: 'Admin' },
  'role.manager': { kk: 'Менеджер', ru: 'Менеджер', en: 'Manager' },
  'role.agent': { kk: 'Инженер', ru: 'Инженер', en: 'Engineer' },
  'role.employee': { kk: 'Қолданушы', ru: 'Пользователь', en: 'User' },

  // Dashboard
  'dashboard.welcome': { kk: 'Сәлем', ru: 'Привет', en: 'Hello' },
  'dashboard.howAreYou': { kk: 'Бүгінгі жағдайыңыз қалай?', ru: 'Как ваши дела сегодня?', en: 'How are you today?' },
  'dashboard.allTickets': { kk: 'Барлық тикеттер', ru: 'Все заявки', en: 'All Tickets' },
  'dashboard.new': { kk: 'Жаңа', ru: 'Новые', en: 'New' },
  'dashboard.inProgress': { kk: 'Орындалуда', ru: 'В работе', en: 'In Progress' },
  'dashboard.slaBreach': { kk: 'SLA бұзылған', ru: 'SLA нарушено', en: 'SLA Breached' },
  'dashboard.recentTickets': { kk: 'Соңғы тикеттер', ru: 'Последние заявки', en: 'Recent Tickets' },
  'dashboard.noTickets': { kk: 'Тикеттер жоқ', ru: 'Заявок нет', en: 'No tickets' },
  'dashboard.createTicket': { kk: 'Жаңа тикет жасау', ru: 'Создать заявку', en: 'Create Ticket' },
  'dashboard.viewAll': { kk: 'Барлығы', ru: 'Все', en: 'View All' },
  'dashboard.allTicketsInSystem': { kk: 'Жүйедегі барлық тикеттер', ru: 'Все заявки в системе', en: 'All tickets in system' },
  'dashboard.unprocessedTickets': { kk: 'Өңделмеген тикеттер', ru: 'Необработанные заявки', en: 'Unprocessed tickets' },
  'dashboard.workingTickets': { kk: 'Жұмыс істеп жатқан', ru: 'В процессе работы', en: 'Currently working' },
  'dashboard.overdueTickets': { kk: 'Мерзімі өткен', ru: 'Просроченные', en: 'Overdue' },
  'dashboard.recentlyCreated': { kk: 'Жақында жасалған тикеттер', ru: 'Недавно созданные заявки', en: 'Recently created tickets' },
  'dashboard.employeeKpi.title': { kk: 'Қызметкерлер KPI', ru: 'KPI сотрудников', en: 'Employee KPI' },
  'dashboard.employeeKpi.details': { kk: 'Толығырақ', ru: 'Подробнее', en: 'Details' },
  'dashboard.employeeKpi.average': { kk: 'Орташа KPI', ru: 'Средний KPI', en: 'Average KPI' },
  'dashboard.employeeKpi.resolved': { kk: 'Шешілді', ru: 'Решено', en: 'Resolved' },
  'dashboard.employeeKpi.reaction': { kk: 'Реакция', ru: 'Реакция', en: 'Response' },
  'dashboard.employeeKpi.minutes': { kk: 'мин', ru: 'мин', en: 'min' },
  'dashboard.employeeKpi.empty': { kk: 'KPI есептеу үшін әзірге деректер жоқ.', ru: 'Пока нет данных для расчёта KPI.', en: 'No data for KPI calculation yet.' },
  'dashboard.employeeKpi.resolvedCount': { kk: 'шешілді', ru: 'решено', en: 'resolved' },
  'dashboard.employeeKpi.position.firstLine': { kk: 'Бірінші желі инженері', ru: 'Инженер первой линии', en: 'First line engineer' },
  'dashboard.employeeKpi.position.secondLine': { kk: 'Екінші желі инженері', ru: 'Инженер второй линии', en: 'Second line engineer' },
  'dashboard.employeeKpi.position.thirdLine': { kk: 'Үшінші желі инженері', ru: 'Инженер третьей линии', en: 'Third line engineer' },

  // Tickets
  'ticket.new': { kk: 'Жаңа тикет', ru: 'Новая заявка', en: 'New Ticket' },
  'ticket.search': { kk: 'Тикеттерді іздеу...', ru: 'Поиск заявок...', en: 'Search tickets...' },
  'ticket.status.new': { kk: 'Жаңа', ru: 'Новая', en: 'New' },
  'ticket.status.assigned': { kk: 'Тағайындалған', ru: 'Назначено', en: 'Assigned' },
  'ticket.status.inProgress': { kk: 'Орындалуда', ru: 'В работе', en: 'In Progress' },
  'ticket.status.resolved': { kk: 'Шешілген', ru: 'Решена', en: 'Resolved' },
  'ticket.status.closed': { kk: 'Жабылған', ru: 'Закрыта', en: 'Closed' },
  'ticket.status.reopened': { kk: 'Қайта ашылған', ru: 'Переоткрыта', en: 'Reopened' },
  'ticket.priority.low': { kk: 'Төмен', ru: 'Низкий', en: 'Low' },
  'ticket.priority.medium': { kk: 'Орташа', ru: 'Средний', en: 'Medium' },
  'ticket.priority.high': { kk: 'Жоғары', ru: 'Высокий', en: 'High' },
  'ticket.priority.critical': { kk: 'Шұғыл', ru: 'Критический', en: 'Critical' },
  'ticket.list.title': { kk: 'Тикеттер', ru: 'Заявки', en: 'Tickets' },
  'ticket.list.subtitle': { kk: 'Барлық тикеттерді басқару', ru: 'Управление всеми заявками', en: 'Manage all tickets' },
  'ticket.list.searchPlaceholder': { kk: 'Іздеу...', ru: 'Поиск...', en: 'Search...' },
  'ticket.list.allStatuses': { kk: 'Барлық статустар', ru: 'Все статусы', en: 'All statuses' },
  'ticket.list.allPriorities': { kk: 'Барлық маңыздылық', ru: 'Все приоритеты', en: 'All priorities' },
  'ticket.list.visibleOf': { kk: 'көрсетілді, барлығы', ru: 'показано из', en: 'shown of' },
  'ticket.list.stats.active': { kk: 'Белсенді тикеттер', ru: 'Активные заявки', en: 'Active tickets' },
  'ticket.list.stats.urgent': { kk: 'Жоғары басымдық', ru: 'Высокий приоритет', en: 'High priority' },
  'ticket.list.stats.unassigned': { kk: 'Орындаушысыз', ru: 'Без исполнителя', en: 'Unassigned' },
  'ticket.list.stats.done': { kk: 'Аяқталған', ru: 'Завершено', en: 'Done' },
  'ticket.list.noTickets': { kk: 'Тикеттер табылмады', ru: 'Заявки не найдены', en: 'No tickets found' },
  'ticket.list.header.title': { kk: 'Тақырып', ru: 'Тема', en: 'Title' },
  'ticket.list.header.requester': { kk: 'Сұраушы', ru: 'Заявитель', en: 'Requester' },
  'ticket.list.header.status': { kk: 'Статус', ru: 'Статус', en: 'Status' },
  'ticket.list.header.priority': { kk: 'Маңыздылық', ru: 'Приоритет', en: 'Priority' },
  'ticket.list.header.assignee': { kk: 'Тағайындалған', ru: 'Назначено', en: 'Assigned' },
  'ticket.list.header.date': { kk: 'Күні', ru: 'Дата', en: 'Date' },
  'ticket.form.title': { kk: 'Жаңа тикет', ru: 'Новая заявка', en: 'New Ticket' },
  'ticket.form.subtitle': { kk: 'Жаңа сұрау жасау', ru: 'Создать новую заявку', en: 'Create a new request' },
  'ticket.form.details': { kk: 'Тикет мәліметтері', ru: 'Детали заявки', en: 'Ticket Details' },
  'ticket.form.detailsDesc': { kk: 'Мәселеңізді мүмкіндігінше толық сипаттаңыз', ru: 'Опишите вашу проблему как можно подробнее', en: 'Describe your issue as detailed as possible' },
  'ticket.form.titleLabel': { kk: 'Тақырып', ru: 'Тема', en: 'Title' },
  'ticket.form.titlePlaceholder': { kk: 'Мәселені қысқаша сипаттаңыз', ru: 'Кратко опишите проблему', en: 'Briefly describe the issue' },
  'ticket.form.description': { kk: 'Сипаттама', ru: 'Описание', en: 'Description' },
  'ticket.form.descriptionPlaceholder': { kk: 'Мәселені толық сипаттаңыз...', ru: 'Подробно опишите проблему...', en: 'Describe the issue in detail...' },
  'ticket.form.requester': { kk: 'Өтініш беруші', ru: 'Заявитель', en: 'Requester' },
  'ticket.form.selectRequester': { kk: 'Өтініш берушіні таңдаңыз', ru: 'Выберите заявителя', en: 'Select requester' },
  'ticket.form.assignee': { kk: 'Орындаушы', ru: 'Исполнитель', en: 'Assignee' },
  'ticket.form.selectAssignee': { kk: 'Орындаушыны таңдаңыз', ru: 'Выберите исполнителя', en: 'Select assignee' },
  'ticket.form.priority': { kk: 'Маңыздылық', ru: 'Приоритет', en: 'Priority' },
  'ticket.form.category': { kk: 'Категория', ru: 'Категория', en: 'Category' },
  'ticket.form.selectCategory': { kk: 'Таңдаңыз', ru: 'Выберите', en: 'Select' },
  'ticket.form.planning': { kk: 'Жоспарлау', ru: 'Планирование', en: 'Planning' },
  'ticket.form.planningDesc': { kk: 'Өтінімді нақты күн мен уақытқа жоспарлау', ru: 'Запланировать заявку на конкретную дату и время', en: 'Schedule the ticket for a specific date and time' },
  'ticket.form.plannedDate': { kk: 'Күні', ru: 'Дата', en: 'Date' },
  'ticket.form.plannedStart': { kk: 'Басталу уақыты', ru: 'Время начала', en: 'Start time' },
  'ticket.form.plannedEnd': { kk: 'Аяқталу уақыты', ru: 'Время окончания', en: 'End time' },
  'ticket.form.planningNote': { kk: 'Жоспарлау ескертпесі', ru: 'Примечание к планированию', en: 'Planning note' },
  'ticket.form.planningNotePlaceholder': { kk: 'Жұмыс терезесін, шарттарын немесе дайындықты көрсетіңіз...', ru: 'Укажите окно работ, условия или подготовку...', en: 'Specify the work window, conditions, or preparation...' },
  'ticket.form.planningRequired': { kk: 'Жоспарлау үшін күн мен басталу уақытын көрсетіңіз', ru: 'Для планирования укажите дату и время начала', en: 'Select date and start time for planning' },
  'ticket.form.planningEndError': { kk: 'Аяқталу уақыты басталу уақытынан кейін болуы керек', ru: 'Время окончания должно быть позже времени начала', en: 'End time must be later than start time' },
  'ticket.form.submit': { kk: 'Тикет жасау', ru: 'Создать заявку', en: 'Create Ticket' },
  'ticket.form.attachmentsUploadError': { kk: 'Тикет жасалды, бірақ тіркемелер жүктелмеді', ru: 'Заявка создана, но вложения не загрузились', en: 'Ticket created, but attachments failed to upload' },

  // Ticket Detail
  'ticket.detail.description': { kk: 'Сипаттама', ru: 'Описание', en: 'Description' },
  'ticket.detail.noDescription': { kk: 'Сипаттама жоқ', ru: 'Описание отсутствует', en: 'No description' },
  'ticket.detail.attachments': { kk: 'Тіркемелер', ru: 'Вложения', en: 'Attachments' },
  'ticket.detail.uploadFile': { kk: 'Файл жүктеу', ru: 'Загрузить файл', en: 'Upload File' },
  'ticket.detail.noAttachments': { kk: 'Тіркемелер жоқ', ru: 'Вложений нет', en: 'No attachments' },
  'ticket.detail.comments': { kk: 'Пікірлер', ru: 'Комментарии', en: 'Comments' },
  'ticket.detail.commentsDiscussion': { kk: 'Тикет бойынша талқылау', ru: 'Обсуждение по заявке', en: 'Discussion on this ticket' },
  'ticket.detail.noComments': { kk: 'Пікірлер жоқ', ru: 'Комментариев нет', en: 'No comments' },
  'ticket.detail.commentPlaceholder': { kk: 'Пікір жазыңыз...', ru: 'Напишите комментарий...', en: 'Write a comment...' },
  'ticket.detail.send': { kk: 'Жіберу', ru: 'Отправить', en: 'Send' },
  'ticket.detail.details': { kk: 'Мәліметтер', ru: 'Детали', en: 'Details' },
  'ticket.detail.planning': { kk: 'Жоспарлау', ru: 'Планирование', en: 'Planning' },
  'ticket.detail.plannedStart': { kk: 'Басталу уақыты', ru: 'Начало', en: 'Start' },
  'ticket.detail.plannedEnd': { kk: 'Аяқталу уақыты', ru: 'Окончание', en: 'End' },
  'ticket.detail.planningNote': { kk: 'Ескертпе', ru: 'Примечание', en: 'Note' },
  'ticket.detail.requester': { kk: 'Сұраушы', ru: 'Заявитель', en: 'Requester' },
  'ticket.detail.createdDate': { kk: 'Жасалған күні', ru: 'Дата создания', en: 'Created Date' },
  'ticket.detail.management': { kk: 'Басқару', ru: 'Управление', en: 'Management' },
  'ticket.detail.status': { kk: 'Статус', ru: 'Статус', en: 'Status' },
  'ticket.detail.assigned': { kk: 'Тағайындалған', ru: 'Назначено', en: 'Assigned' },
  'ticket.detail.unassigned': { kk: 'Тағайындалмаған', ru: 'Не назначено', en: 'Unassigned' },
  'ticket.detail.notFound': { kk: 'Тикет табылмады', ru: 'Заявка не найдена', en: 'Ticket not found' },
  'ticket.detail.backToTickets': { kk: 'Тикеттерге оралу', ru: 'Вернуться к заявкам', en: 'Back to tickets' },
  'ticket.detail.unknown': { kk: 'Белгісіз', ru: 'Неизвестно', en: 'Unknown' },

  // Common
  'common.save': { kk: 'Сақтау', ru: 'Сохранить', en: 'Save' },
  'common.cancel': { kk: 'Болдырмау', ru: 'Отмена', en: 'Cancel' },
  'common.close': { kk: 'Жабу', ru: 'Закрыть', en: 'Close' },
  'common.delete': { kk: 'Жою', ru: 'Удалить', en: 'Delete' },
  'common.edit': { kk: 'Өзгерту', ru: 'Редактировать', en: 'Edit' },
  'common.create': { kk: 'Жасау', ru: 'Создать', en: 'Create' },
  'common.loading': { kk: 'Жүктелуде...', ru: 'Загрузка...', en: 'Loading...' },
  'common.error': { kk: 'Қате', ru: 'Ошибка', en: 'Error' },
  'common.success': { kk: 'Сәтті!', ru: 'Успешно!', en: 'Success!' },
  'common.unknown': { kk: 'Белгісіз', ru: 'Неизвестно', en: 'Unknown' },
  'common.notifications': { kk: 'Хабарландырулар', ru: 'Уведомления', en: 'Notifications' },
  'common.viewAll': { kk: 'Барлығын көру', ru: 'Показать все', en: 'View all' },
  'common.back': { kk: 'Артқа', ru: 'Назад', en: 'Back' },
  'common.add': { kk: 'Қосу', ru: 'Добавить', en: 'Add' },
  'common.search': { kk: 'Іздеу...', ru: 'Поиск...', en: 'Search...' },
  'common.select': { kk: 'Таңдаңыз', ru: 'Выберите', en: 'Select' },
  'common.name': { kk: 'Атауы', ru: 'Название', en: 'Name' },
  'common.description': { kk: 'Сипаттама', ru: 'Описание', en: 'Description' },
  'common.status': { kk: 'Статус', ru: 'Статус', en: 'Status' },
  'common.date': { kk: 'Күні', ru: 'Дата', en: 'Date' },
  'common.export': { kk: 'Экспорт', ru: 'Экспорт', en: 'Export' },
  'common.all': { kk: 'Барлығы', ru: 'Все', en: 'All' },
  'common.enableAll': { kk: 'Қосу', ru: 'Вкл.', en: 'Enable' },
  'common.disableAll': { kk: 'Өшіру', ru: 'Выкл.', en: 'Disable' },
  'common.reset': { kk: 'Қалпына келтіру', ru: 'Сбросить', en: 'Reset' },
  'common.you': { kk: 'Сіз', ru: 'Вы', en: 'You' },
  'common.markAllRead': { kk: 'Барлығын оқу', ru: 'Прочитать все', en: 'Mark all read' },
  'common.noNotifications': { kk: 'Хабарландырулар жоқ', ru: 'Нет уведомлений', en: 'No notifications' },
  'common.chatHistory': { kk: 'Чат тарихы', ru: 'История чата', en: 'Chat history' },
  'common.unknownUser': { kk: 'Белгісіз қолданушы', ru: 'Неизвестный пользователь', en: 'Unknown user' },
  'layout.collapseSidebar': { kk: 'Бүйір панельді жинау', ru: 'Свернуть боковую панель', en: 'Collapse sidebar' },
  'layout.expandSidebar': { kk: 'Бүйір панельді ашу', ru: 'Развернуть боковую панель', en: 'Expand sidebar' },

  // Auth
  'auth.login': { kk: 'Кіру', ru: 'Вход', en: 'Login' },
  'auth.register': { kk: 'Тіркелу', ru: 'Регистрация', en: 'Register' },
  'auth.email': { kk: 'Электрондық пошта', ru: 'Эл. почта', en: 'Email' },
  'auth.password': { kk: 'Құпия сөз', ru: 'Пароль', en: 'Password' },
  'auth.confirmPassword': { kk: 'Құпия сөзді қайталаңыз', ru: 'Повторите пароль', en: 'Confirm Password' },
  'auth.name': { kk: 'Аты-жөні', ru: 'ФИО', en: 'Full Name' },
  'auth.namePlaceholder': { kk: 'Тегі Аты Әкесінің аты', ru: 'Имя Фамилия Отчество', en: 'Surname First Name Patronymic' },
  'auth.fullNameRequired': { kk: 'Аты-жөніңізді толық енгізіңіз: аты, тегі және әкесінің аты', ru: 'Введите ФИО полностью: имя, фамилию и отчество через пробел', en: 'Enter your full name completely: first name, last name, and patronymic separated by spaces' },
  'auth.noAccount': { kk: 'Аккаунтыңыз жоқ па?', ru: 'Нет аккаунта?', en: "Don't have an account?" },
  'auth.hasAccount': { kk: 'Аккаунтыңыз бар ма?', ru: 'Есть аккаунт?', en: 'Already have an account?' },
  'auth.helpdesk': { kk: 'ITSM & Service Desk жүйесіне кіру', ru: 'Вход в систему ITSM & Service Desk', en: 'Login to ITSM & Service Desk' },
  'auth.2fa': { kk: 'Екі факторлы тексеру', ru: 'Двухфакторная аутентификация', en: 'Two-Factor Authentication' },
  'auth.enterOtp': { kk: 'Authenticator қосымшасындағы 6 санды кодты енгізіңіз', ru: 'Введите 6-значный код из приложения Authenticator', en: 'Enter the 6-digit code from your Authenticator app' },
  'auth.verify': { kk: 'Тексеру', ru: 'Проверить', en: 'Verify' },
  'auth.back': { kk: 'Артқа', ru: 'Назад', en: 'Back' },
  'auth.createAccount': { kk: 'Жаңа аккаунт құрыңыз', ru: 'Создайте новый аккаунт', en: 'Create a new account' },
  'auth.confirmEmail': { kk: 'Электрондық поштаңызды растаңыз', ru: 'Подтвердите вашу эл. почту', en: 'Please confirm your email' },
  'auth.wrongCredentials': { kk: 'Электрондық пошта немесе құпия сөз қате', ru: 'Неверный email или пароль', en: 'Invalid email or password' },
  'auth.forgotPassword': { kk: 'Құпия сөзді ұмыттыңыз ба?', ru: 'Забыли пароль?', en: 'Forgot password?' },
  'auth.resetPassword': { kk: 'Құпия сөзді өзгерту', ru: 'Сменить пароль', en: 'Change password' },
  'auth.newPassword': { kk: 'Жаңа құпия сөз', ru: 'Новый пароль', en: 'New password' },
  'auth.resetPasswordDesc': { kk: 'Email енгізіңіз. Қалпына келтіру коды қысқа уақытқа ғана жарамды.', ru: 'Введите email. Код восстановления действует ограниченное время.', en: 'Enter your email. The reset code is valid for a limited time.' },
  'auth.sendResetCode': { kk: 'Код жіберу', ru: 'Отправить код', en: 'Send code' },
  'auth.resetCode': { kk: 'Қалпына келтіру коды', ru: 'Код восстановления', en: 'Reset code' },
  'auth.resetTokenSent': { kk: 'Егер email тіркелген болса, қалпына келтіру коды жіберілді.', ru: 'Если email зарегистрирован, код восстановления отправлен.', en: 'If the email is registered, a reset code has been sent.' },
  'auth.passwordChanged': { kk: 'Құпия сөз өзгертілді. Енді жаңа құпия сөзбен кіріңіз.', ru: 'Пароль изменен. Теперь войдите с новым паролем.', en: 'Password changed. You can now sign in with the new password.' },
  'auth.passwordMismatch': { kk: 'Құпия сөздер сәйкес келмейді', ru: 'Пароли не совпадают', en: 'Passwords do not match' },
  'auth.passwordTooShort': { kk: 'Құпия сөз кем дегенде 6 таңбадан тұруы керек', ru: 'Пароль должен содержать минимум 6 символов', en: 'Password must be at least 6 characters' },
  'auth.registerHeroEyebrow': { kk: 'Qazaq Generation платформасы', ru: 'Платформа Qazaq Generation', en: 'Qazaq Generation Platform' },
  'auth.registerHeroTitle': { kk: 'Компанияның сервистік процестерін басқаруға арналған бірыңғай платформа', ru: 'Единая платформа для управления сервисными процессами компании', en: 'A unified platform for managing enterprise service operations' },
  'auth.registerHeroSubtitle': { kk: 'Өтінімдер, активтер, білім базасы және команда жұмысы бір қауіпсіз ITSM кеңістігінде.', ru: 'Заявки, активы, база знаний и работа команды в одном безопасном ITSM-пространстве.', en: 'Tickets, assets, knowledge base, and teamwork in one secure ITSM workspace.' },
  'auth.enterpriseReady': { kk: 'Enterprise-ready', ru: 'Enterprise-ready', en: 'Enterprise-ready' },
  'auth.secureAccess': { kk: 'Қауіпсіз қолжетімділік', ru: 'Безопасный доступ', en: 'Secure access' },
  'auth.serviceDesk': { kk: 'Service Desk орталығы', ru: 'Центр Service Desk', en: 'Service Desk hub' },

  // Profile
  'profile.title': { kk: 'Профиль', ru: 'Профиль', en: 'Profile' },
  'profile.subtitle': { kk: 'Аккаунт параметрлері', ru: 'Настройки аккаунта', en: 'Account settings' },
  'profile.avatar': { kk: 'Аватар', ru: 'Аватар', en: 'Avatar' },
  'profile.changeAvatar': { kk: 'Фото өзгерту', ru: 'Изменить фото', en: 'Change photo' },
  'profile.uploadPhoto': { kk: 'Фото жүктеу', ru: 'Загрузить фото', en: 'Upload photo' },
  'profile.removePhoto': { kk: 'Фотоны жою', ru: 'Удалить фото', en: 'Remove photo' },
  'profile.avatarUploadError': { kk: 'Суретті жүктеу мүмкін болмады', ru: 'Не удалось загрузить изображение', en: 'Could not load the image' },
  'profile.name': { kk: 'Аты-жөні', ru: 'ФИО', en: 'Full Name' },
  'profile.email': { kk: 'Электрондық пошта', ru: 'Эл. почта', en: 'Email' },
  'profile.department': { kk: 'Бөлім', ru: 'Отдел', en: 'Department' },
  'profile.role': { kk: 'Рөлі', ru: 'Роль', en: 'Role' },
  'profile.stats': { kk: 'Статистика', ru: 'Статистика', en: 'Statistics' },
  'profile.ticketsClosed': { kk: 'Жабылған тикеттер', ru: 'Закрытых заявок', en: 'Tickets closed' },
  'profile.avgResolution': { kk: 'Орташа шешу уақыты', ru: 'Среднее время решения', en: 'Avg resolution time' },
  'profile.slaSuccess': { kk: 'SLA сәттілігі', ru: 'Успешность SLA', en: 'SLA success rate' },
  'profile.updateSuccess': { kk: 'Профиль жаңартылды', ru: 'Профиль обновлен', en: 'Profile updated' },

  // AI Chat
  'ai.title': { kk: 'AI Ассистент', ru: 'AI Ассистент', en: 'AI Assistant' },
  'ai.subtitle': { kk: 'Сұрақтарыңызға жауап беремін', ru: 'Отвечу на ваши вопросы', en: 'I will answer your questions' },
  'ai.placeholder': { kk: 'Сұрағыңызды жазыңыз...', ru: 'Напишите ваш вопрос...', en: 'Type your question...' },
  'ai.send': { kk: 'Жіберу', ru: 'Отправить', en: 'Send' },
  'ai.thinking': { kk: 'Ойланып жатырмын...', ru: 'Думаю...', en: 'Thinking...' },
  'ai.welcome': { kk: 'Сәлем! Мен сіздің AI көмекшіңізбін. Сұрақтарыңызға жауап беруге дайынмын.', ru: 'Привет! Я ваш AI помощник. Готов ответить на ваши вопросы.', en: 'Hello! I am your AI assistant. Ready to answer your questions.' },
  'ai.general': { kk: 'Жалпы', ru: 'Общий', en: 'General' },
  'ai.ticketAnalysis': { kk: 'Тикет талдау', ru: 'Анализ тикетов', en: 'Ticket Analysis' },
  'ai.reportGeneration': { kk: 'Есеп құру', ru: 'Генерация отчётов', en: 'Reports' },

  // Admin - Users
  'admin.users.title': { kk: 'Қолданушыларды басқару', ru: 'Управление пользователями', en: 'Users Management' },
  'admin.users.subtitle': { kk: 'Қолданушылардың рөлдері мен бөлімдерін басқару', ru: 'Управление ролями и отделами пользователей', en: 'Manage user roles and departments' },
  'admin.users.editUser': { kk: 'Қолданушыны өңдеу', ru: 'Редактировать пользователя', en: 'Edit User' },
  'admin.users.editDesc': { kk: 'Қолданушы деректерін өзгертіңіз', ru: 'Измените данные пользователя', en: 'Change user details' },
  'admin.users.name': { kk: 'Аты', ru: 'Имя', en: 'Name' },
  'admin.users.role': { kk: 'Рөл', ru: 'Роль', en: 'Role' },
  'admin.users.department': { kk: 'Бөлім', ru: 'Отдел', en: 'Department' },
  'admin.users.group': { kk: 'Топ', ru: 'Группа', en: 'Group' },
  'admin.users.registered': { kk: 'Тіркелген', ru: 'Зарегистрирован', en: 'Registered' },
  'admin.users.updated': { kk: 'Қолданушы деректері жаңартылды', ru: 'Данные пользователя обновлены', en: 'User data updated' },
  'admin.users.loadError': { kk: 'Қолданушыларды жүктеу кезінде қате', ru: 'Ошибка загрузки пользователей', en: 'Error loading users' },
  'admin.users.updateError': { kk: 'Қолданушыны жаңарту кезінде қате', ru: 'Ошибка обновления пользователя', en: 'Error updating user' },

  // Admin - Departments
  'admin.depts.title': { kk: 'Бөлімдер мен топтар', ru: 'Отделы и группы', en: 'Departments & Groups' },
  'admin.depts.subtitle': { kk: 'Ұйым құрылымын басқару', ru: 'Управление структурой организации', en: 'Manage organization structure' },
  'admin.depts.addDept': { kk: 'Бөлім қосу', ru: 'Добавить отдел', en: 'Add Department' },
  'admin.depts.addGroup': { kk: 'Топ қосу', ru: 'Добавить группу', en: 'Add Group' },
  'admin.depts.newDept': { kk: 'Жаңа бөлім', ru: 'Новый отдел', en: 'New Department' },
  'admin.depts.newDeptDesc': { kk: 'Жаңа бөлім атауын енгізіңіз', ru: 'Введите название нового отдела', en: 'Enter the new department name' },
  'admin.depts.newGroup': { kk: 'Жаңа топ', ru: 'Новая группа', en: 'New Group' },
  'admin.depts.newGroupDesc': { kk: 'Бөлімге жаңа топ қосыңыз', ru: 'Добавьте новую группу в отдел', en: 'Add a new group to a department' },
  'admin.depts.departments': { kk: 'Бөлімдер', ru: 'Отделы', en: 'Departments' },
  'admin.depts.groups': { kk: 'Топтар', ru: 'Группы', en: 'Groups' },
  'admin.depts.groupName': { kk: 'Топ атауы', ru: 'Название группы', en: 'Group Name' },
  'admin.depts.editDept': { kk: 'Бөлімді өңдеу', ru: 'Редактировать отдел', en: 'Edit Department' },
  'admin.depts.deptAdded': { kk: 'Бөлім қосылды', ru: 'Отдел добавлен', en: 'Department added' },
  'admin.depts.deptUpdated': { kk: 'Бөлім жаңартылды', ru: 'Отдел обновлён', en: 'Department updated' },
  'admin.depts.groupAdded': { kk: 'Топ қосылды', ru: 'Группа добавлена', en: 'Group added' },
  'admin.depts.deptPlaceholder': { kk: 'Мысалы: IT бөлімі', ru: 'Например: IT отдел', en: 'e.g. IT Department' },
  'admin.depts.groupPlaceholder': { kk: 'Мысалы: IT қолдау', ru: 'Например: IT поддержка', en: 'e.g. IT Support' },

  // Admin - Categories
  'admin.cats.title': { kk: 'Категориялар', ru: 'Категории', en: 'Categories' },
  'admin.cats.subtitle': { kk: 'Тикет категорияларын басқару', ru: 'Управление категориями заявок', en: 'Manage ticket categories' },
  'admin.cats.addCategory': { kk: 'Категория қосу', ru: 'Добавить категорию', en: 'Add Category' },
  'admin.cats.newCategory': { kk: 'Жаңа категория', ru: 'Новая категория', en: 'New Category' },
  'admin.cats.newCatDesc': { kk: 'Тикеттер үшін жаңа категория жасаңыз', ru: 'Создайте новую категорию для заявок', en: 'Create a new category for tickets' },
  'admin.cats.editCategory': { kk: 'Категорияны өңдеу', ru: 'Редактировать категорию', en: 'Edit Category' },
  'admin.cats.allCategories': { kk: 'Барлық категориялар', ru: 'Все категории', en: 'All Categories' },
  'admin.cats.created': { kk: 'Құрылған', ru: 'Создан', en: 'Created' },
  'admin.cats.catAdded': { kk: 'Категория қосылды', ru: 'Категория добавлена', en: 'Category added' },
  'admin.cats.catUpdated': { kk: 'Категория жаңартылды', ru: 'Категория обновлена', en: 'Category updated' },
  'admin.cats.catPlaceholder': { kk: 'Мысалы: Техникалық қолдау', ru: 'Например: Техническая поддержка', en: 'e.g. Technical Support' },
  'admin.cats.descPlaceholder': { kk: 'Категория сипаттамасы', ru: 'Описание категории', en: 'Category description' },

  // Admin - SLA
  'admin.sla.title': { kk: 'SLA саясаттары', ru: 'SLA политики', en: 'SLA Policies' },
  'admin.sla.subtitle': { kk: 'Қызмет көрсету деңгейі келісімдерін басқару', ru: 'Управление соглашениями уровня обслуживания', en: 'Manage service level agreements' },
  'admin.sla.addSla': { kk: 'SLA қосу', ru: 'Добавить SLA', en: 'Add SLA' },
  'admin.sla.newSla': { kk: 'Жаңа SLA саясаты', ru: 'Новая SLA политика', en: 'New SLA Policy' },
  'admin.sla.newSlaDesc': { kk: 'Жаңа қызмет көрсету деңгейі келісімін жасаңыз', ru: 'Создайте новое соглашение уровня обслуживания', en: 'Create a new service level agreement' },
  'admin.sla.editSla': { kk: 'SLA саясатын өңдеу', ru: 'Редактировать SLA политику', en: 'Edit SLA Policy' },
  'admin.sla.priority': { kk: 'Приоритет', ru: 'Приоритет', en: 'Priority' },
  'admin.sla.category': { kk: 'Категория (міндетті емес)', ru: 'Категория (необязательно)', en: 'Category (optional)' },
  'admin.sla.allCategories': { kk: 'Барлық категориялар', ru: 'Все категории', en: 'All categories' },
  'admin.sla.responseTime': { kk: 'Жауап беру (минут)', ru: 'Время ответа (минут)', en: 'Response Time (minutes)' },
  'admin.sla.resolveTime': { kk: 'Шешу (минут)', ru: 'Время решения (минут)', en: 'Resolution Time (minutes)' },
  'admin.sla.policies': { kk: 'Белгіленген саясаттар', ru: 'Установленные политики', en: 'Configured Policies' },
  'admin.sla.policiesDesc': { kk: 'Приоритет пен категория бойынша SLA мерзімдері', ru: 'Сроки SLA по приоритету и категории', en: 'SLA deadlines by priority and category' },
  'admin.sla.response': { kk: 'Жауап беру', ru: 'Ответ', en: 'Response' },
  'admin.sla.resolve': { kk: 'Шешу', ru: 'Решение', en: 'Resolution' },
  'admin.sla.slaAdded': { kk: 'SLA саясаты қосылды', ru: 'SLA политика добавлена', en: 'SLA policy added' },
  'admin.sla.slaUpdated': { kk: 'SLA саясаты жаңартылды', ru: 'SLA политика обновлена', en: 'SLA policy updated' },
  'admin.sla.min': { kk: 'мин', ru: 'мин', en: 'min' },
  'admin.sla.hour': { kk: 'сағ', ru: 'ч', en: 'h' },

  // Notification Settings
  'notifSettings.title': { kk: 'Хабарландыру баптаулары', ru: 'Настройки уведомлений', en: 'Notification Settings' },
  'notifSettings.subtitle': { kk: 'Қандай оқиғалар бойынша және қай каналдар арқылы хабарландыру алғыңыз келетінін таңдаңыз', ru: 'Выберите какие события и через какие каналы вы хотите получать уведомления', en: 'Choose which events and channels you want to receive notifications through' },
  'notifSettings.pushEnabled': { kk: 'Push хабарландырулар қосылған', ru: 'Push-уведомления включены', en: 'Push notifications enabled' },
  'notifSettings.pushDisabled': { kk: 'Push хабарландыруларды қосу үшін рұқсат беріңіз', ru: 'Разрешите push-уведомления для их получения', en: 'Allow push notifications to receive them' },
  'notifSettings.eventsAndChannels': { kk: 'Оқиғалар мен каналдар', ru: 'События и каналы', en: 'Events & Channels' },
  'notifSettings.eventsDesc': { kk: 'Әр оқиға түрі үшін каналдарды қосыңыз немесе өшіріңіз', ru: 'Включите или отключите каналы для каждого типа событий', en: 'Enable or disable channels for each event type' },
  'notifSettings.statusChange': { kk: 'Статус өзгерісі', ru: 'Изменение статуса', en: 'Status Change' },
  'notifSettings.statusChangeDesc': { kk: 'Тикет статусы өзгергенде хабарландыру', ru: 'Уведомление при изменении статуса заявки', en: 'Notification when ticket status changes' },
  'notifSettings.assignment': { kk: 'Тағайындау', ru: 'Назначение', en: 'Assignment' },
  'notifSettings.assignmentDesc': { kk: 'Тикет сізге тағайындалғанда хабарландыру', ru: 'Уведомление при назначении заявки на вас', en: 'Notification when a ticket is assigned to you' },
  'notifSettings.comment': { kk: 'Жаңа пікір', ru: 'Новый комментарий', en: 'New Comment' },
  'notifSettings.commentDesc': { kk: 'Тикетке жаңа пікір қосылғанда хабарландыру', ru: 'Уведомление при новом комментарии к заявке', en: 'Notification when a new comment is added' },
  'notifSettings.slaBreach': { kk: 'SLA бұзушылық', ru: 'Нарушение SLA', en: 'SLA Breach' },
  'notifSettings.slaBreachDesc': { kk: 'SLA мерзімі бұзылғанда хабарландыру', ru: 'Уведомление при нарушении сроков SLA', en: 'Notification when SLA deadlines are breached' },
  'notifSettings.saved': { kk: 'Хабарландыру баптаулары сақталды', ru: 'Настройки уведомлений сохранены', en: 'Notification settings saved' },

  // Notifications List
  'notifList.title': { kk: 'Хабарландырулар', ru: 'Уведомления', en: 'Notifications' },
  'notifList.unread': { kk: 'оқылмаған', ru: 'непрочитанных', en: 'unread' },
  'notifList.allTypes': { kk: 'Барлық түрлер', ru: 'Все типы', en: 'All types' },
  'notifList.markAllRead': { kk: 'Барлығын оқу', ru: 'Прочитать все', en: 'Mark all read' },
  'notifList.noNotifications': { kk: 'Хабарландырулар жоқ', ru: 'Нет уведомлений', en: 'No notifications' },
  'notifList.statusChanged': { kk: 'Статус өзгерді', ru: 'Изменение статуса', en: 'Status Changed' },
  'notifList.assigned': { kk: 'Тағайындау', ru: 'Назначение', en: 'Assignment' },
  'notifList.newComment': { kk: 'Жаңа пікір', ru: 'Новый комментарий', en: 'New Comment' },
  'notifList.slaBreach': { kk: 'SLA бұзылды', ru: 'Нарушение SLA', en: 'SLA Breach' },
  'notifList.meetingInvite': { kk: 'Конференцияға шақыру', ru: 'Приглашение в конференцию', en: 'Meeting invite' },
  'notifList.notifications': { kk: 'хабарландыру', ru: 'уведомлений', en: 'notifications' },

  // PPR Plans
  'ppr.title': { kk: 'ППР - Жоспарлы-алдын алу жұмыстары', ru: 'ППР - Планово-предупредительные работы', en: 'PPR - Preventive Maintenance' },
  'ppr.subtitle': { kk: 'ППР жасау, қол қою және бақылау', ru: 'Создание, подписание и контроль выполнения ППР', en: 'Create, sign and monitor PPR execution' },
  'ppr.createPpr': { kk: 'ППР жасау', ru: 'Создать ППР', en: 'Create PPR' },
  'ppr.newPlan': { kk: 'Жаңа ППР жоспары', ru: 'Новый план ППР', en: 'New PPR Plan' },
  'ppr.planName': { kk: 'Атауы', ru: 'Название', en: 'Name' },
  'ppr.equipment': { kk: 'Жабдық', ru: 'Оборудование', en: 'Equipment' },
  'ppr.location': { kk: 'Орналасуы', ru: 'Расположение', en: 'Location' },
  'ppr.scheduledDate': { kk: 'Күні', ru: 'Дата', en: 'Date' },
  'ppr.frequency': { kk: 'Жиілігі', ru: 'Периодичность', en: 'Frequency' },
  'ppr.daily': { kk: 'Күнделікті', ru: 'Ежедневно', en: 'Daily' },
  'ppr.weekly': { kk: 'Апта сайын', ru: 'Еженедельно', en: 'Weekly' },
  'ppr.monthly': { kk: 'Ай сайын', ru: 'Ежемесячно', en: 'Monthly' },
  'ppr.quarterly': { kk: 'Тоқсан сайын', ru: 'Ежеквартально', en: 'Quarterly' },
  'ppr.yearly': { kk: 'Жыл сайын', ru: 'Ежегодно', en: 'Yearly' },
  'ppr.description': { kk: 'Сипаттама', ru: 'Описание', en: 'Description' },
  'ppr.checklist': { kk: 'Тексеру тізімі', ru: 'Чек-лист', en: 'Checklist' },
  'ppr.createPlan': { kk: 'Жоспар жасау', ru: 'Создать план', en: 'Create Plan' },
  'ppr.noPlans': { kk: 'ППР жоспарлары жоқ. Біріншісін жасаңыз!', ru: 'ППР планов пока нет. Создайте первый!', en: 'No PPR plans yet. Create the first one!' },
  'ppr.draft': { kk: 'Жоба', ru: 'Черновик', en: 'Draft' },
  'ppr.inProgress': { kk: 'Орындалуда', ru: 'В работе', en: 'In Progress' },
  'ppr.signedExecutor': { kk: 'Орындаушы қол қойды', ru: 'Подписан исполнителем', en: 'Signed by Executor' },
  'ppr.approved': { kk: 'Бекітілді', ru: 'Утверждён', en: 'Approved' },
  'ppr.rejected': { kk: 'Қабылданбады', ru: 'Отклонён', en: 'Rejected' },
  'ppr.overdue': { kk: 'Мерзімі өтті', ru: 'Просрочен', en: 'Overdue' },
  'ppr.createdBy': { kk: 'Жасаған', ru: 'Создал', en: 'Created by' },
  'ppr.signatures': { kk: 'Қолтаңбалар', ru: 'Подписи', en: 'Signatures' },
  'ppr.executor': { kk: 'Орындаушы', ru: 'Исполнитель', en: 'Executor' },
  'ppr.manager': { kk: 'Жетекші', ru: 'Руководитель', en: 'Manager' },
  'ppr.signed': { kk: 'Қол қойылды', ru: 'Подписано', en: 'Signed' },
  'ppr.approvedStatus': { kk: 'Бекітілді', ru: 'Утверждено', en: 'Approved' },
  'ppr.sign': { kk: 'Қол қою', ru: 'Подписать', en: 'Sign' },
  'ppr.approve': { kk: 'Бекіту', ru: 'Утвердить', en: 'Approve' },
  'ppr.reject': { kk: 'Қабылдамау', ru: 'Отклонить', en: 'Reject' },
  'ppr.awaitingSignature': { kk: 'Қол қоюды күтуде', ru: 'Ожидает подписи', en: 'Awaiting signature' },
  'ppr.awaitingApproval': { kk: 'Бекітуді күтуде', ru: 'Ожидает утверждения', en: 'Awaiting approval' },
  'ppr.executorFirst': { kk: 'Алдымен орындаушы қол қоюы керек', ru: 'Сначала подпись исполнителя', en: 'Executor must sign first' },
  'ppr.planCreated': { kk: 'ППР жоспар жасалды', ru: 'ППР план создан', en: 'PPR plan created' },
  'ppr.signedSuccess': { kk: 'Сәтті қол қойылды', ru: 'Подписано успешно', en: 'Signed successfully' },
  'ppr.equipmentPlaceholder': { kk: 'HP DL380 сервері', ru: 'Сервер HP DL380', en: 'HP DL380 Server' },
  'ppr.locationPlaceholder': { kk: 'Серверлік, 101 бөлме', ru: 'Серверная, комната 101', en: 'Server room, Room 101' },
  'ppr.namePlaceholder': { kk: 'Серверлерге ай сайынғы ТО', ru: 'Ежемесячное ТО серверов', en: 'Monthly server maintenance' },
  'ppr.descPlaceholder': { kk: 'Жұмыстардың толық сипаттамасы...', ru: 'Подробное описание работ...', en: 'Detailed description of work...' },
  'ppr.point': { kk: 'Пункт', ru: 'Пункт', en: 'Item' },

  // Reports / Analytics
  'reports.title': { kk: 'Есептер мен аналитика', ru: 'Отчёты и аналитика', en: 'Reports & Analytics' },
  'reports.subtitle': { kk: 'Тикеттер статистикасы және өнімділік көрсеткіштері', ru: 'Статистика заявок и показатели производительности', en: 'Ticket statistics and performance metrics' },
  'reports.lastWeek': { kk: 'Соңғы апта', ru: 'За неделю', en: 'Last Week' },
  'reports.thisMonth': { kk: 'Бұл ай', ru: 'Этот месяц', en: 'This Month' },
  'reports.last90days': { kk: 'Соңғы 90 күн', ru: 'За 90 дней', en: 'Last 90 Days' },
  'reports.allTickets': { kk: 'Барлық тикеттер', ru: 'Все заявки', en: 'All Tickets' },
  'reports.resolved': { kk: 'Шешілген', ru: 'Решено', en: 'Resolved' },
  'reports.inProgress': { kk: 'Орындалуда', ru: 'В работе', en: 'In Progress' },
  'reports.slaBreached': { kk: 'SLA бұзылған', ru: 'SLA нарушено', en: 'SLA Breached' },
  'reports.overview': { kk: 'Жалпы көрініс', ru: 'Обзор', en: 'Overview' },
  'reports.trends': { kk: 'Трендтер', ru: 'Тренды', en: 'Trends' },
  'reports.categories': { kk: 'Категориялар', ru: 'Категории', en: 'Categories' },
  'reports.byStatus': { kk: 'Статус бойынша', ru: 'По статусу', en: 'By Status' },
  'reports.byPriority': { kk: 'Приоритет бойынша', ru: 'По приоритету', en: 'By Priority' },
  'reports.dailyTrend': { kk: 'Күнделікті тренд', ru: 'Дневной тренд', en: 'Daily Trend' },
  'reports.created': { kk: 'Жасалған', ru: 'Создано', en: 'Created' },
  'reports.topCategories': { kk: 'Топ категориялар', ru: 'Топ категории', en: 'Top Categories' },

  // Reports Management
  'reportsManage.title': { kk: 'Есептер', ru: 'Отчёты', en: 'Reports' },
  'reportsManage.subtitle': { kk: 'AI көмегімен есептер жасау және басқару', ru: 'Создание и управление отчётами с помощью AI', en: 'Create and manage reports with AI assistance' },
  'reportsManage.newReport': { kk: 'Жаңа есеп', ru: 'Новый отчёт', en: 'New Report' },
  'reportsManage.createTitle': { kk: 'Жаңа есеп жасау', ru: 'Создать новый отчёт', en: 'Create New Report' },
  'reportsManage.createDesc': { kk: 'AI көмегімен автоматты есеп жасаңыз немесе қолмен жазыңыз', ru: 'Создайте автоматический отчёт с помощью AI или напишите вручную', en: 'Generate an automatic report with AI or write manually' },
  'reportsManage.reportTitle': { kk: 'Атауы', ru: 'Название', en: 'Title' },
  'reportsManage.period': { kk: 'Кезең', ru: 'Период', en: 'Period' },
  'reportsManage.generateAI': { kk: 'AI көмегімен жасау', ru: 'Сгенерировать с AI', en: 'Generate with AI' },
  'reportsManage.content': { kk: 'Мазмұны', ru: 'Содержание', en: 'Content' },
  'reportsManage.contentPlaceholder': { kk: 'Есеп мазмұны...', ru: 'Содержание отчёта...', en: 'Report content...' },
  'reportsManage.allReports': { kk: 'Барлық есептер', ru: 'Все отчёты', en: 'All Reports' },
  'nav.tools.performance': { kk: 'Қызметкерлер KPI', ru: 'KPI сотрудников', en: 'Employee KPI' },
  'reportsManage.noReports': { kk: 'Есептер жоқ', ru: 'Отчётов нет', en: 'No reports' },
  'reportsManage.aiReady': { kk: 'AI есебі дайын', ru: 'AI отчёт готов', en: 'AI report ready' },
  'reportsManage.saved': { kk: 'Есеп сақталды', ru: 'Отчёт сохранён', en: 'Report saved' },
  'reportsManage.titlePlaceholder': { kk: 'Апталық есеп', ru: 'Еженедельный отчёт', en: 'Weekly report' },

  // Assets
  'assets.title': { kk: 'Активтерді басқару (CMDB)', ru: 'Управление активами (CMDB)', en: 'Asset Management (CMDB)' },
  'assets.subtitle': { kk: 'Жабдық, бағдарламалар және лицензиялар есебі', ru: 'Учёт оборудования, ПО и лицензий', en: 'Equipment, software and license tracking' },
  'assets.addAsset': { kk: 'Актив қосу', ru: 'Добавить актив', en: 'Add Asset' },
  'assets.exportCsv': { kk: 'Excel экспорт', ru: 'Экспорт Excel', en: 'Export Excel' },
  'assets.exportDone': { kk: 'Экспорт сәтті', ru: 'Экспорт завершён', en: 'Export complete' },
  'assets.editAsset': { kk: 'Активті өзгерту', ru: 'Редактировать актив', en: 'Edit Asset' },
  'assets.newAsset': { kk: 'Жаңа актив', ru: 'Новый актив', en: 'New Asset' },
  'assets.assetCreated': { kk: 'Актив жасалды', ru: 'Актив создан', en: 'Asset created' },
  'assets.assetUpdated': { kk: 'Актив жаңартылды', ru: 'Актив обновлён', en: 'Asset updated' },
  'assets.assetDeleted': { kk: 'Актив жойылды', ru: 'Актив удалён', en: 'Asset deleted' },
  'assets.noAssets': { kk: 'Активтер табылмады', ru: 'Активы не найдены', en: 'No assets found' },
  'assets.type': { kk: 'Тип', ru: 'Тип', en: 'Type' },
  'assets.allTypes': { kk: 'Барлық типтер', ru: 'Все типы', en: 'All types' },
  'assets.allStatuses': { kk: 'Барлық статустар', ru: 'Все статусы', en: 'All statuses' },
  'assets.list': { kk: 'Тізім', ru: 'Список', en: 'List' },
  'assets.templates': { kk: 'Шаблондар', ru: 'Шаблоны', en: 'Templates' },
  'assets.selected': { kk: 'Таңдалды', ru: 'Выбрано', en: 'Selected' },
  'assets.deleteSelected': { kk: 'Таңдалғандарды жою', ru: 'Удалить выбранные', en: 'Delete selected' },
  'assets.selectPage': { kk: 'Бетті таңдау', ru: 'Выбрать страницу', en: 'Select page' },
  'assets.organization': { kk: 'Ұйым', ru: 'Организация', en: 'Organization' },
  'assets.networkIp': { kk: 'Желілік құрылым - IP', ru: 'Сетевая структура - IP', en: 'Network structure - IP' },
  'assets.user': { kk: 'Қолданушы', ru: 'Пользователь', en: 'User' },
  'assets.comments': { kk: 'Пікірлер', ru: 'Комментарии', en: 'Comments' },
  'assets.operatingSystem': { kk: 'Операциялық жүйе', ru: 'Операционная система', en: 'Operating System' },
  'assets.rowsPerPage': { kk: 'беттегі жолдар', ru: 'строк на странице', en: 'rows per page' },
  'assets.paginationSummary': { kk: '{total} ішінен {from}-{to} жолдары көрсетілуде', ru: 'Отображаются строки с {from} по {to} из {total}', en: 'Showing rows {from} to {to} of {total}' },
  'assets.serialNumber': { kk: 'Сериялық №', ru: 'Серийный №', en: 'Serial #' },
  'assets.inventoryNumber': { kk: 'Инвентарлық №', ru: 'Инвентарный №', en: 'Inventory #' },
  'assets.manufacturer': { kk: 'Өндіруші', ru: 'Производитель', en: 'Manufacturer' },
  'assets.model': { kk: 'Модель', ru: 'Модель', en: 'Model' },
  'assets.location': { kk: 'Орналасуы', ru: 'Местоположение', en: 'Location' },
  'assets.purchaseDate': { kk: 'Сатып алу күні', ru: 'Дата покупки', en: 'Purchase Date' },
  'assets.warranty': { kk: 'Кепілдік мерзімі', ru: 'Гарантия до', en: 'Warranty Expiry' },
  'assets.cost': { kk: 'Бағасы', ru: 'Стоимость', en: 'Cost' },
  'assets.notes': { kk: 'Ескертпелер', ru: 'Заметки', en: 'Notes' },
  'assets.hardware': { kk: 'Жабдық', ru: 'Оборудование', en: 'Hardware' },
  'assets.software': { kk: 'Бағдарлама', ru: 'ПО', en: 'Software' },
  'assets.license': { kk: 'Лицензия', ru: 'Лицензия', en: 'License' },
  'assets.network': { kk: 'Желі', ru: 'Сеть', en: 'Network' },
  'assets.peripheral': { kk: 'Перифери', ru: 'Периферия', en: 'Peripheral' },
  'assets.active': { kk: 'Белсенді', ru: 'Активный', en: 'Active' },
  'assets.inStock': { kk: 'Қоймада', ru: 'На складе', en: 'In Stock' },
  'assets.maintenance': { kk: 'Жөндеуде', ru: 'На обслуживании', en: 'Maintenance' },
  'assets.retired': { kk: 'Шығарылған', ru: 'Списан', en: 'Retired' },
  'assets.disposed': { kk: 'Жойылған', ru: 'Утилизирован', en: 'Disposed' },

  // Dashboard extras
  'dashboard.highPriority': { kk: 'Жоғары приоритет', ru: 'Высокий приоритет', en: 'High Priority' },
  'dashboard.highPriorityDesc': { kk: 'High / Critical', ru: 'High / Critical', en: 'High / Critical' },
  'dashboard.unassigned': { kk: 'Тағайындалмаған', ru: 'Не назначено', en: 'Unassigned' },
  'dashboard.unassignedDesc': { kk: 'Исполнитель жоқ', ru: 'Без исполнителя', en: 'No assignee' },
  'dashboard.quickActions': { kk: 'Жылдам әрекеттер', ru: 'Быстрые действия', en: 'Quick Actions' },
  'dashboard.qa.createTicket': { kk: 'Тикет жасау', ru: 'Создать заявку', en: 'Create Ticket' },
  'dashboard.qa.assign': { kk: 'Тағайындау', ru: 'Назначить', en: 'Assign' },
  'dashboard.qa.exportReport': { kk: 'Есеп экспорт', ru: 'Экспорт отчёта', en: 'Export Report' },
  'dashboard.qa.addUser': { kk: 'Қызметкер қосу', ru: 'Добавить сотрудника', en: 'Add Employee' },
  'dashboard.qa.slaSetup': { kk: 'SLA баптау', ru: 'Настройка SLA', en: 'SLA Setup' },
  'dashboard.qa.aiAssistant': { kk: 'AI ассистент', ru: 'AI ассистент', en: 'AI Assistant' },
  'dashboard.filters': { kk: 'Сүзгілер', ru: 'Фильтры', en: 'Filters' },
  'dashboard.filter.period': { kk: 'Кезең', ru: 'Период', en: 'Period' },
  'dashboard.filter.allTime': { kk: 'Барлық уақыт', ru: 'Все время', en: 'All time' },
  'dashboard.filter.today': { kk: 'Бүгін', ru: 'Сегодня', en: 'Today' },
  'dashboard.filter.week': { kk: 'Апта ішінде', ru: 'За неделю', en: 'This week' },
  'dashboard.filter.month': { kk: 'Ай ішінде', ru: 'За месяц', en: 'This month' },
  'dashboard.filter.priority': { kk: 'Басымдық', ru: 'Приоритет', en: 'Priority' },
  'dashboard.filter.status': { kk: 'Күйі', ru: 'Статус', en: 'Status' },
  'dashboard.filter.department': { kk: 'Бөлім', ru: 'Отдел', en: 'Department' },
  'dashboard.filter.assignee': { kk: 'Орындаушы', ru: 'Исполнитель', en: 'Assignee' },
  'dashboard.filter.allDepartments': { kk: 'Барлық бөлімдер', ru: 'Все отделы', en: 'All departments' },
  'dashboard.filter.reset': { kk: 'Қалпына келтіру', ru: 'Сбросить', en: 'Reset' },
  'dashboard.attentionRequired': { kk: 'Шұғыл назар қажет', ru: 'Требует срочного внимания', en: 'Needs attention' },
  'dashboard.teamWorkload': { kk: 'Команда жүктемесі', ru: 'Загрузка команды', en: 'Team workload' },
  'dashboard.recentActivity': { kk: 'Соңғы әрекеттер', ru: 'Последние действия', en: 'Recent activity' },
  'dashboard.noActivity': { kk: 'Әрекеттер жоқ', ru: 'Нет действий', en: 'No activity yet' },
  'dashboard.noData': { kk: 'Дерек жоқ', ru: 'Нет данных', en: 'No data' },
  'dashboard.last7Days': { kk: 'Соңғы 7 күндегі тикеттер', ru: 'Заявки за 7 дней', en: 'Tickets in the last 7 days' },
  'dashboard.trendByDay': { kk: 'Күндер бойынша тренд', ru: 'Тренд по дням', en: 'Trend by day' },
  'dashboard.byStatus': { kk: 'Статус бойынша', ru: 'По статусу', en: 'By status' },
  'dashboard.ticketDistribution': { kk: 'Тикеттердің бөлінуі', ru: 'Распределение заявок', en: 'Ticket distribution' },
  'dashboard.byPriority': { kk: 'Басымдық бойынша', ru: 'По приоритету', en: 'By priority' },
  'dashboard.priorityDistribution': { kk: 'Маңыздылық бойынша бөлінуі', ru: 'Распределение по важности', en: 'Priority distribution' },
  'dashboard.slaWithin': { kk: 'SLA шегіндегі тикеттер', ru: 'Заявки в рамках SLA', en: 'Tickets within SLA' },
  'dashboard.workload.low': { kk: 'Төмен', ru: 'Низкая', en: 'Low' },
  'dashboard.workload.medium': { kk: 'Орташа', ru: 'Средняя', en: 'Medium' },
  'dashboard.workload.high': { kk: 'Жоғары', ru: 'Высокая', en: 'High' },
  'dashboard.ticketsShort': { kk: 'тикет', ru: 'заяв.', en: 'tickets' },
  'dashboard.minutesShort': { kk: 'мин', ru: 'мин', en: 'min' },
  'dashboard.activity.status': { kk: 'статусты өзгертті', ru: 'изменил статус', en: 'changed the status' },
  'dashboard.activity.priority': { kk: 'басымдықты өзгертті', ru: 'изменил приоритет', en: 'changed the priority' },
  'dashboard.activity.assignee': { kk: 'орындаушыны тағайындады', ru: 'назначил исполнителя', en: 'assigned an assignee' },
  'dashboard.activity.category': { kk: 'категорияны өзгертті', ru: 'изменил категорию', en: 'changed the category' },
  'dashboard.activity.comment': { kk: 'пікір қосты', ru: 'добавил комментарий', en: 'added a comment' },

  // Profile push notifications
  'profile.pushTitle': { kk: 'Push хабарландырулар', ru: 'Push-уведомления', en: 'Push Notifications' },
  'profile.pushDesc': { kk: 'Браузерде push хабарландыруларды қосыңыз', ru: 'Включите push-уведомления в браузере', en: 'Enable push notifications in browser' },
  'profile.pushEnabled': { kk: 'Push қосылған', ru: 'Push включены', en: 'Push enabled' },
  'profile.pushDisabled': { kk: 'Push өшірулі', ru: 'Push отключены', en: 'Push disabled' },
  'profile.pushHint': { kk: 'Тикет өзгерістері туралы бірден хабар алыңыз', ru: 'Получайте мгновенные уведомления об изменениях заявок', en: 'Get instant notifications about ticket changes' },

  // Chat
  'chat.title': { kk: 'Хабарламалар', ru: 'Сообщения', en: 'Messages' },
  'chat.chats': { kk: 'Чаттар', ru: 'Чаты', en: 'Chats' },
  'chat.noChats': { kk: 'Чаттар жоқ', ru: 'Нет чатов', en: 'No chats yet' },
  'chat.people': { kk: 'Қызметкерлер', ru: 'Сотрудники', en: 'People' },
  'chat.noPeople': { kk: 'Қызметкерлер табылмады', ru: 'Сотрудники не найдены', en: 'No people found' },
  'chat.members': { kk: 'мүше', ru: 'участн.', en: 'members' },
  'chat.direct': { kk: 'Жеке чат', ru: 'Личный чат', en: 'Direct' },
  'chat.noMessages': { kk: 'Хабарлама жоқ. Біріншісін жазыңыз!', ru: 'Нет сообщений. Напишите первое!', en: 'No messages yet. Write the first one!' },
  'chat.typePlaceholder': { kk: 'Хабарлама жазыңыз...', ru: 'Напишите сообщение...', en: 'Type a message...' },
  'chat.selectChat': { kk: 'Чатты таңдаңыз', ru: 'Выберите чат', en: 'Select a chat' },
  'chat.startNew': { kk: 'Немесе жаңа сөйлесу бастаңыз', ru: 'Или начните новую беседу', en: 'Or start a new conversation' },
  'chat.newGroup': { kk: 'Жаңа группа', ru: 'Новая группа', en: 'New Group' },
  'chat.groupName': { kk: 'Группа атауы', ru: 'Название группы', en: 'Group Name' },
  'chat.groupPlaceholder': { kk: 'Мысалы: IT бөлімі', ru: 'Например: Отдел IT', en: 'e.g. IT Department' },
  'chat.groupMembers': { kk: 'Мүшелер', ru: 'Участники', en: 'Members' },
  'chat.you': { kk: 'Сіз', ru: 'Вы', en: 'You' },
  'chat.today': { kk: 'Бүгін', ru: 'Сегодня', en: 'Today' },
  'chat.yesterday': { kk: 'Кеше', ru: 'Вчера', en: 'Yesterday' },
  'chat.customize': { kk: 'Чатты баптау', ru: 'Настроить чат', en: 'Customize chat' },
  'chat.background': { kk: 'Фон', ru: 'Фон', en: 'Background' },
  'chat.avatarUrl': { kk: 'Аватар сілтемесі', ru: 'Ссылка на аватарку', en: 'Avatar URL' },
  'chat.avatarPhoto': { kk: 'Аватар фотосы', ru: 'Фото аватарки', en: 'Avatar photo' },
  'chat.uploadAvatar': { kk: 'Фото жүктеу', ru: 'Загрузить фото', en: 'Upload photo' },
  'chat.avatarHint': { kk: 'Фото жүктеңіз, суретке сілтеме қойыңыз немесе өрісті бос қалдырыңыз.', ru: 'Загрузите фото, вставьте ссылку на картинку или оставьте поле пустым.', en: 'Upload a photo, paste an image link, or leave the field empty.' },
  'chat.avatarSaved': { kk: 'Аватар жаңартылды', ru: 'Аватарка обновлена', en: 'Avatar updated' },
  'chat.avatarUploadError': { kk: 'Суретті жүктеу мүмкін болмады', ru: 'Не удалось загрузить изображение', en: 'Could not load the image' },
  'chat.attachFile': { kk: 'Файл тіркеу', ru: 'Прикрепить файл', en: 'Attach file' },
  'chat.recordVoice': { kk: 'Дауыстық хабарлама жазу', ru: 'Записать голосовое сообщение', en: 'Record voice message' },
  'chat.stopRecording': { kk: 'Жазуды тоқтату', ru: 'Остановить запись', en: 'Stop recording' },
  'chat.microphoneDenied': { kk: 'Микрофонға рұқсат берілмеді', ru: 'Нет доступа к микрофону', en: 'Microphone access was denied' },

  // Knowledge Base
  'kb.title': { kk: 'Білім қоры', ru: 'База знаний', en: 'Knowledge Base' },
  'kb.subtitle': { kk: 'Мақалалар, нұсқаулықтар және жиі қойылатын сұрақтар', ru: 'Статьи, инструкции и часто задаваемые вопросы', en: 'Articles, guides and frequently asked questions' },
  'kb.newArticle': { kk: 'Жаңа мақала', ru: 'Новая статья', en: 'New Article' },
  'kb.editArticle': { kk: 'Мақаланы өңдеу', ru: 'Редактировать статью', en: 'Edit Article' },
  'kb.editorDesc': { kk: 'Мақала деректерін толтырыңыз', ru: 'Заполните данные статьи', en: 'Fill in the article details' },
  'kb.articleTitle': { kk: 'Тақырып', ru: 'Заголовок', en: 'Title' },
  'kb.titlePlaceholder': { kk: 'Мысалы: Принтерді қалай қосуға болады', ru: 'Например: Как подключить принтер', en: 'e.g. How to connect a printer' },
  'kb.shortDesc': { kk: 'Қысқаша сипаттама', ru: 'Краткое описание', en: 'Short Description' },
  'kb.shortDescPlaceholder': { kk: 'Мақаланың қысқаша мазмұны', ru: 'Краткое содержание статьи', en: 'Brief article summary' },
  'kb.content': { kk: 'Мазмұны', ru: 'Содержание', en: 'Content' },
  'kb.contentPlaceholder': { kk: 'Толық мазмұнды жазыңыз (Markdown қолдайды)...', ru: 'Напишите полное содержание (поддерживается Markdown)...', en: 'Write full content (Markdown supported)...' },
  'kb.category': { kk: 'Категория', ru: 'Категория', en: 'Category' },
  'kb.visibility': { kk: 'Көрінуі', ru: 'Видимость', en: 'Visibility' },
  'kb.public': { kk: 'Ашық', ru: 'Публичная', en: 'Public' },
  'kb.internal': { kk: 'Ішкі', ru: 'Внутренняя', en: 'Internal' },
  'kb.tags': { kk: 'Тегтер', ru: 'Теги', en: 'Tags' },
  'kb.tagsPlaceholder': { kk: 'Үтір арқылы бөліңіз: принтер, желі, қосу', ru: 'Через запятую: принтер, сеть, подключение', en: 'Comma separated: printer, network, setup' },
  'kb.searchPlaceholder': { kk: 'Мақалаларды іздеу...', ru: 'Поиск статей...', en: 'Search articles...' },
  'kb.allCategories': { kk: 'Барлық категориялар', ru: 'Все категории', en: 'All Categories' },
  'kb.allVisibility': { kk: 'Барлық көрінуі', ru: 'Вся видимость', en: 'All Visibility' },
  'kb.noArticles': { kk: 'Мақалалар табылмады', ru: 'Статьи не найдены', en: 'No articles found' },
  'kb.addCategory': { kk: 'Категория қосу', ru: 'Добавить категорию', en: 'Add Category' },
  'kb.categoryPlaceholder': { kk: 'Мысалы: Желілік мәселелер', ru: 'Например: Сетевые вопросы', en: 'e.g. Network Issues' },
  'kb.categoryCreated': { kk: 'Категория жасалды', ru: 'Категория создана', en: 'Category created' },
  'kb.articleCreated': { kk: 'Мақала жасалды', ru: 'Статья создана', en: 'Article created' },
  'kb.articleUpdated': { kk: 'Мақала жаңартылды', ru: 'Статья обновлена', en: 'Article updated' },
  'kb.articleDeleted': { kk: 'Мақала жойылды', ru: 'Статья удалена', en: 'Article deleted' },
  'kb.articleNotFound': { kk: 'Мақала табылмады', ru: 'Статья не найдена', en: 'Article not found' },
  'kb.updated': { kk: 'Жаңартылды', ru: 'Обновлено', en: 'Updated' },
  'kb.views': { kk: 'көрілім', ru: 'просмотров', en: 'views' },
  'kb.linkedArticles': { kk: 'Байланысты мақалалар', ru: 'Связанные статьи', en: 'Linked Articles' },
  'kb.linkArticle': { kk: 'Мақала байланыстыру', ru: 'Привязать статью', en: 'Link Article' },
  'kb.noLinkedArticles': { kk: 'Байланысты мақалалар жоқ', ru: 'Нет связанных статей', en: 'No linked articles' },
  'kb.searchAndLink': { kk: 'Мақала іздеу және байланыстыру', ru: 'Поиск и привязка статьи', en: 'Search & Link Article' },
  'kb.articleLinked': { kk: 'Мақала байланыстырылды', ru: 'Статья привязана', en: 'Article linked' },
  'kb.alreadyLinked': { kk: 'Қосылған', ru: 'Привязана', en: 'Linked' },

  // Navigation - Documents
  'nav.documents': { kk: 'Құжаттар', ru: 'Документы', en: 'Documents' },

  // Documents module
  'docs.title': { kk: 'Құжаттар және есептілік', ru: 'Документы и отчётность', en: 'Documents and Reports' },
  'docs.subtitle': { kk: 'Word және Excel форматында құжат жасап, Messenger арқылы қызметкерлерге жіберіңіз', ru: 'Создавайте документы в Word и Excel и отправляйте отчётность сотрудникам через Messenger', en: 'Create Word and Excel documents and send reports to employees through Messenger' },
  'docs.templates': { kk: 'Шаблондар', ru: 'Шаблоны', en: 'Templates' },
  'docs.blankDoc': { kk: 'Бос құжат', ru: 'Пустой документ', en: 'Blank Document' },
  'docs.blankSheet': { kk: 'Бос кесте', ru: 'Пустая таблица', en: 'Blank Spreadsheet' },
  'docs.reportTemplate': { kk: 'Тикеттер бойынша есеп', ru: 'Отчёт по заявкам', en: 'Ticket Report' },
  'docs.memoTemplate': { kk: 'Қызметтік жазба', ru: 'Служебная записка', en: 'Memo' },
  'docs.actTemplate': { kk: 'Орындалған жұмыс актісі', ru: 'Акт выполненных работ', en: 'Work Completion Act' },
  'docs.inventoryTemplate': { kk: 'Инвентаризация тізімі', ru: 'Инвентаризационная ведомость', en: 'Inventory List' },
  'docs.ticketReportTemplate': { kk: 'Тикеттер есебі', ru: 'Отчёт по тикетам', en: 'Ticket Report' },
  'docs.actFromTicket': { kk: 'Тикеттен акт жасау', ru: 'Сформировать акт из тикета', en: 'Generate Act from Ticket' },
  'docs.enterTicketId': { kk: 'Тикет ID енгізіңіз', ru: 'Введите ID тикета', en: 'Enter Ticket ID' },
  'docs.generateAct': { kk: 'Акт жасау', ru: 'Сформировать акт', en: 'Generate Act' },
  'docs.download': { kk: 'Жүктеу', ru: 'Скачать', en: 'Download' },
  'docs.downloaded': { kk: 'Құжат жүктелді', ru: 'Документ скачан', en: 'Document downloaded' },
  'docs.insertImage': { kk: 'Сурет енгізу', ru: 'Вставить изображение', en: 'Insert image' },
  'docs.templateApplied': { kk: 'Шаблон қолданылды', ru: 'Шаблон применён', en: 'Template applied' },
  'docs.ticketNotFound': { kk: 'Тикет табылмады', ru: 'Тикет не найден', en: 'Ticket not found' },
  'docs.documentTitle': { kk: 'Құжат тақырыбы', ru: 'Заголовок документа', en: 'Document Title' },
  'docs.enterTextHere': { kk: 'Мәтінді осында енгізіңіз...', ru: 'Введите текст здесь...', en: 'Enter text here...' },
  'docs.actTitle': { kk: 'ОРЫНДАЛҒАН ЖҰМЫС АКТІСІ', ru: 'АКТ ВЫПОЛНЕННЫХ РАБОТ', en: 'WORK COMPLETION ACT' },
  'docs.date': { kk: 'Күні', ru: 'Дата', en: 'Date' },
  'docs.ticketNumber': { kk: 'Тикет нөмірі', ru: 'Номер заявки', en: 'Ticket Number' },
  'docs.category': { kk: 'Категория', ru: 'Категория', en: 'Category' },
  'docs.priority': { kk: 'Басымдық', ru: 'Приоритет', en: 'Priority' },
  'docs.status': { kk: 'Күйі', ru: 'Статус', en: 'Status' },
  'docs.subject': { kk: 'Тақырып', ru: 'Тема', en: 'Subject' },
  'docs.description': { kk: 'Сипаттама', ru: 'Описание', en: 'Description' },
  'docs.workPerformed': { kk: 'Орындалған жұмыс', ru: 'Выполненные работы', en: 'Work Performed' },
  'docs.executor': { kk: 'Орындаушы', ru: 'Исполнитель', en: 'Executor' },
  'docs.customer': { kk: 'Тапсырыс беруші', ru: 'Заказчик', en: 'Customer' },
  'docs.signature': { kk: 'Қолы', ru: 'Подпись', en: 'Signature' },
  'docs.ticketReport': { kk: 'ТИКЕТТЕР БОЙЫНША ЕСЕП', ru: 'ОТЧЁТ ПО ЗАЯВКАМ', en: 'TICKET REPORT' },
  'docs.summary': { kk: 'Қысқаша', ru: 'Резюме', en: 'Summary' },
  'docs.details': { kk: 'Толық мәлімет', ru: 'Детали', en: 'Details' },
  'docs.conclusions': { kk: 'Қорытынды', ru: 'Выводы', en: 'Conclusions' },
  'docs.enterSummaryHere': { kk: 'Қысқаша мәлімет енгізіңіз...', ru: 'Введите резюме...', en: 'Enter summary...' },
  'docs.enterDetailsHere': { kk: 'Толық мәлімет енгізіңіз...', ru: 'Введите детали...', en: 'Enter details...' },
  'docs.enterConclusionsHere': { kk: 'Қорытынды енгізіңіз...', ru: 'Введите выводы...', en: 'Enter conclusions...' },
  'docs.memo': { kk: 'ҚЫЗМЕТТІК ЖАЗБА', ru: 'СЛУЖЕБНАЯ ЗАПИСКА', en: 'MEMO' },
  'docs.from': { kk: 'Кімнен', ru: 'От кого', en: 'From' },
  'docs.to': { kk: 'Кімге', ru: 'Кому', en: 'To' },
  'docs.author': { kk: 'Автор', ru: 'Автор', en: 'Author' },
  'docs.paragraph': { kk: 'Абзац', ru: 'Абзац', en: 'Paragraph' },
  'docs.heading': { kk: 'Тақырып', ru: 'Заголовок', en: 'Heading' },
  'docs.addRow': { kk: 'Жол', ru: 'Строка', en: 'Row' },
  'docs.addCol': { kk: 'Баған', ru: 'Столбец', en: 'Column' },
  'docs.delRow': { kk: 'Жолды өшіру', ru: 'Удалить строку', en: 'Delete Row' },
  'docs.delCol': { kk: 'Бағанды өшіру', ru: 'Удалить столбец', en: 'Delete Column' },
  'docs.assetName': { kk: 'Атауы', ru: 'Название', en: 'Name' },
  'docs.assetType': { kk: 'Түрі', ru: 'Тип', en: 'Type' },
  'docs.serialNumber': { kk: 'Сериялық нөмір', ru: 'Серийный номер', en: 'Serial Number' },
  'docs.inventoryNumber': { kk: 'Инвентарлық нөмір', ru: 'Инвентарный номер', en: 'Inventory Number' },
  'docs.location': { kk: 'Орналасқан жері', ru: 'Расположение', en: 'Location' },
  'docs.manufacturer': { kk: 'Өндіруші', ru: 'Производитель', en: 'Manufacturer' },
  'docs.model': { kk: 'Үлгісі', ru: 'Модель', en: 'Model' },
  'docs.createdAt': { kk: 'Жасалған күні', ru: 'Дата создания', en: 'Created' },
  'docs.closedAt': { kk: 'Жабылған күні', ru: 'Дата закрытия', en: 'Closed' },

  // Document sharing
  'docs.inbox': { kk: 'Кіріс құжаттар', ru: 'Входящие', en: 'Inbox' },
  'docs.sendDocument': { kk: 'Messenger-ге жіберу', ru: 'Отправить в Messenger', en: 'Send to Messenger' },
  'docs.selectRecipient': { kk: 'Алушыны таңдаңыз', ru: 'Выберите получателя', en: 'Select Recipient' },
  'docs.searchUsers': { kk: 'Пайдаланушыны іздеу...', ru: 'Поиск пользователя...', en: 'Search users...' },
  'docs.noUsersFound': { kk: 'Пайдаланушылар табылмады', ru: 'Пользователи не найдены', en: 'No users found' },
  'docs.messageOptional': { kk: 'Хабарлама (міндетті емес)', ru: 'Сообщение (необязательно)', en: 'Message (optional)' },
  'docs.enterMessage': { kk: 'Хабарлама енгізіңіз...', ru: 'Введите сообщение...', en: 'Enter message...' },
  'docs.sendTo': { kk: 'Жіберу:', ru: 'Отправить:', en: 'Send to:' },
  'docs.sending': { kk: 'Жіберілуде...', ru: 'Отправка...', en: 'Sending...' },
  'docs.sentSuccess': { kk: 'Құжат Messenger-ге жіберілді', ru: 'Документ отправлен в Messenger', en: 'Document sent to Messenger' },
  'docs.sendError': { kk: 'Жіберу қатесі', ru: 'Ошибка отправки', en: 'Send error' },
  'docs.file': { kk: 'Файл', ru: 'Файл', en: 'File' },
  'docs.newDocReceived': { kk: 'Жаңа құжат алынды', ru: 'Получен новый документ', en: 'New document received' },
  'docs.docFrom': { kk: 'Құжат жіберуші', ru: 'Документ от', en: 'Document from' },
  'docs.sharedDocs': { kk: 'Ортақ құжаттар', ru: 'Общие документы', en: 'Shared Documents' },
  'docs.received': { kk: 'Кіріс', ru: 'Входящие', en: 'Received' },
  'docs.sent': { kk: 'Шығыс', ru: 'Отправленные', en: 'Sent' },
  'docs.new': { kk: 'Жаңа', ru: 'Новое', en: 'New' },
  'docs.loading': { kk: 'Жүктелуде...', ru: 'Загрузка...', en: 'Loading...' },
  'docs.noDocsReceived': { kk: 'Кіріс құжаттар жоқ', ru: 'Нет входящих документов', en: 'No documents received' },
  'docs.noDocsSent': { kk: 'Шығыс құжаттар жоқ', ru: 'Нет отправленных документов', en: 'No documents sent' },
  'docs.downloadError': { kk: 'Жүктеу қатесі', ru: 'Ошибка загрузки', en: 'Download error' },
  'docs.uploadFile': { kk: 'Файл жүктеу', ru: 'Загрузить файл', en: 'Upload file' },
  'docs.uploadDocx': { kk: '.docx файл жүктеу', ru: 'Загрузить .docx', en: 'Upload .docx' },
  'docs.uploadXlsx': { kk: '.xlsx файл жүктеу', ru: 'Загрузить .xlsx', en: 'Upload .xlsx' },
  'docs.fileLoaded': { kk: 'Файл жүктелді', ru: 'Файл загружен', en: 'File loaded' },
  'docs.fileLoadError': { kk: 'Файл жүктеу қатесі', ru: 'Ошибка загрузки файла', en: 'File load error' },
  'docs.invalidFormat': { kk: 'Жарамсыз формат', ru: 'Неверный формат', en: 'Invalid format' },
  'docs.deleteDoc': { kk: 'Құжатты жою', ru: 'Удалить документ', en: 'Delete document' },
  'docs.docDeleted': { kk: 'Құжат жойылды', ru: 'Документ удалён', en: 'Document deleted' },
  'docs.deleteError': { kk: 'Жою қатесі', ru: 'Ошибка удаления', en: 'Delete error' },
  'docs.confirmDelete': { kk: 'Шынымен жойғыңыз келе ме?', ru: 'Вы уверены, что хотите удалить?', en: 'Are you sure you want to delete?' },
  'docs.preview': { kk: 'Алдын ала қарау', ru: 'Предпросмотр', en: 'Preview' },
  'docs.previewError': { kk: 'Алдын ала қарау қатесі', ru: 'Ошибка предпросмотра', en: 'Preview error' },
  'docs.noPreview': { kk: 'Алдын ала қарау қол жетімді емес', ru: 'Предпросмотр недоступен', en: 'Preview not available' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languages: { code: Language; name: string; flag: string }[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('qg-language') as Language;
      if (saved && ['kk', 'ru', 'en'].includes(saved)) return saved;

      const browserLanguage = window.navigator.language.toLowerCase();
      if (browserLanguage.startsWith('ru')) return 'ru';
      if (browserLanguage.startsWith('en')) return 'en';
    }
    return 'kk';
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('qg-language', lang);
    window.dispatchEvent(new CustomEvent('language-changed', { detail: lang }));
  }, []);

  const t = useCallback((key: string): string => {
    const translation = translations[key];
    if (!translation) return key;
    // Fallback chain prevents mixed-language UI when a single locale string is missing.
    return translation[language] || translation.ru || translation.en || translation.kk || key;
  }, [language]);

  const languages = [
    { code: 'kk' as Language, name: 'Қазақша', flag: '🇰🇿' },
    { code: 'ru' as Language, name: 'Русский', flag: '🇷🇺' },
    { code: 'en' as Language, name: 'English', flag: '🇬🇧' },
  ];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
}
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
